<?php

declare(strict_types=1);

use Marko\DevAi\Rendering\AgentsMdRenderer;

beforeEach(function () {
    $this->renderer = new AgentsMdRenderer();
});

it('renders a complete AGENTS.md with project overview build test code-style security testing sections', function () {
    $result = $this->renderer->render([
        'projectName' => 'Test',
        'projectOverview' => 'Overview text',
        'buildCommands' => ['composer install' => 'Install deps'],
        'testCommands' => ['composer test' => 'Run tests'],
        'codeStyle' => 'PSR-12',
        'security' => 'Use prepared statements',
        'testing' => 'Pest framework',
    ]);
    expect($result->body)->toContain('## Project Overview')
        ->and($result->body)->toContain('## Build Commands')
        ->and($result->body)->toContain('## Test Commands')
        ->and($result->body)->toContain('## Code Style')
        ->and($result->body)->toContain('## Security')
        ->and($result->body)->toContain('## Testing');
});

it('includes Marko commands from composer scripts and #[Command] attributes', function () {
    $result = $this->renderer->render([
        'commands' => [
            ['name' => 'mcp:serve', 'description' => 'Start MCP server'],
            ['name' => 'docs-fts:build', 'description' => 'Build docs index'],
        ],
    ]);
    expect($result->body)->toContain('mcp:serve')
        ->and($result->body)->toContain('docs-fts:build');
});

it('aggregates guidelines from marko/core and third-party contributors deterministically', function () {
    $result = $this->renderer->render([
        'guidelines' => [
            'marko/zfoo' => 'Z guidelines',
            'marko/aaa' => 'A guidelines',
            'marko/core' => 'Core guidelines',
        ],
    ]);
    // core should appear first
    $coreIdx = strpos($result->body, '### marko/core');
    $aaaIdx = strpos($result->body, '### marko/aaa');
    $zfooIdx = strpos($result->body, '### marko/zfoo');
    expect($coreIdx)->toBeLessThan($aaaIdx)
        ->and($aaaIdx)->toBeLessThan($zfooIdx);
});

it('produces byte-for-byte identical output on repeated runs given identical input', function () {
    $input = [
        'projectName' => 'Test',
        'guidelines' => ['marko/core' => 'Core', 'marko/foo' => 'Foo'],
    ];
    $r1 = $this->renderer->render($input);
    $r2 = $this->renderer->render($input);
    expect($r1->body)->toBe($r2->body);
});

it('includes a "do not edit" marker with regeneration instructions', function () {
    $result = $this->renderer->render([]);
    expect($result->body)->toContain('Generated by marko/devai')
        ->and($result->body)->toContain('marko devai:update');
});
