<?php

declare(strict_types=1);

namespace Marko\DevAi\Writing;

class GuidelinesWriter
{
    public const string MARKER_BEGIN = '<!-- BEGIN marko:devai -->';

    public const string MARKER_END = '<!-- END marko:devai -->';

    private const string NOTICE_HEADER = '<!-- Generated by marko devai:update — do not edit between markers; content outside the markers is yours. Run `marko devai:update` to regenerate. -->';

    /** @var list<string> */
    private static array $notices = [];

    public static function write(
        string $path,
        string $generated,
        string $label = 'marko:devai',
    ): WriteOutcome {
        if (!file_exists($path)) {
            $content = self::MARKER_BEGIN . "\n"
                . self::NOTICE_HEADER . "\n"
                . $generated . "\n"
                . self::MARKER_END . "\n";
            file_put_contents($path, $content);

            return WriteOutcome::Created;
        }

        $existing = (string) file_get_contents($path);

        $beginPos = strpos($existing, self::MARKER_BEGIN);
        $endPos = strpos($existing, self::MARKER_END);

        // No valid markers or malformed (BEGIN without END, or END before BEGIN)
        if ($beginPos === false || $endPos === false || $endPos < $beginPos) {
            self::$notices[] = "File '$path' does not contain marko:devai markers. Edit it manually or delete it and run `marko devai:update` to regenerate.";

            return WriteOutcome::SkippedNoMarkers;
        }

        // Replace content between markers
        $before = substr($existing, 0, $beginPos + strlen(self::MARKER_BEGIN));
        $after = substr($existing, $endPos);

        $newContent = $before . "\n"
            . self::NOTICE_HEADER . "\n"
            . $generated . "\n"
            . $after;

        file_put_contents($path, $newContent);

        return WriteOutcome::Updated;
    }

    /** @return list<string> */
    public static function takeNotices(): array
    {
        $notices = self::$notices;
        self::$notices = [];

        return $notices;
    }
}
