<?php

declare(strict_types=1);

namespace Marko\DevAi\Rendering;

use Marko\DevAi\ValueObject\GuidelinesContent;

readonly class AgentsMdRenderer
{
    /**
     * @param array{
     *   projectName?: string,
     *   projectOverview?: string,
     *   buildCommands?: array<string, string>,
     *   testCommands?: array<string, string>,
     *   codeStyle?: string,
     *   security?: string,
     *   testing?: string,
     *   commands?: list<array{name: string, description: string}>,
     *   guidelines?: array<string, string>
     * } $input
     */
    public function render(array $input): GuidelinesContent
    {
        $sections = [];

        // Header
        $sections[] = "<!-- Generated by marko/devai. Do not edit manually. Re-run `marko devai:update` to regenerate. -->\n";
        $sections[] = '# ' . ($input['projectName'] ?? 'Marko Project') . "\n";

        // Project Overview
        if (!empty($input['projectOverview'])) {
            $sections[] = "## Project Overview\n\n" . trim($input['projectOverview']) . "\n";
        }

        // Build commands
        if (!empty($input['buildCommands'])) {
            $sections[] = "## Build Commands\n\n" . $this->formatCommandTable($input['buildCommands']) . "\n";
        }

        // Test commands
        if (!empty($input['testCommands'])) {
            $sections[] = "## Test Commands\n\n" . $this->formatCommandTable($input['testCommands']) . "\n";
        }

        // Code Style
        if (!empty($input['codeStyle'])) {
            $sections[] = "## Code Style\n\n" . trim($input['codeStyle']) . "\n";
        }

        // Security
        if (!empty($input['security'])) {
            $sections[] = "## Security\n\n" . trim($input['security']) . "\n";
        }

        // Testing
        if (!empty($input['testing'])) {
            $sections[] = "## Testing\n\n" . trim($input['testing']) . "\n";
        }

        // Commands from #[Command] attributes
        if (!empty($input['commands'])) {
            $cmdList = "## Available Commands\n\n";
            $sortedCommands = $input['commands'];
            usort($sortedCommands, fn ($a, $b) => $a['name'] <=> $b['name']);
            foreach ($sortedCommands as $cmd) {
                $cmdList .= "- `{$cmd['name']}` — {$cmd['description']}\n";
            }
            $sections[] = $cmdList;
        }

        // Per-package guidelines (deterministic alphabetical order, core first)
        if (!empty($input['guidelines'])) {
            $sections[] = "## Package Guidelines\n";
            $guidelines = $input['guidelines'];
            ksort($guidelines);
            // Core first
            if (isset($guidelines['marko/core'])) {
                $sections[] = "### marko/core\n\n" . trim($guidelines['marko/core']) . "\n";
                unset($guidelines['marko/core']);
            }
            foreach ($guidelines as $package => $content) {
                $sections[] = "### $package\n\n" . trim($content) . "\n";
            }
        }

        return new GuidelinesContent(
            body: implode("\n", $sections),
            filename: 'AGENTS.md',
        );
    }

    /** @param array<string, string> $commands */
    private function formatCommandTable(array $commands): string
    {
        ksort($commands);
        $rows = ['| Command | Description |', '|---------|-------------|'];
        foreach ($commands as $cmd => $desc) {
            $rows[] = "| `$cmd` | $desc |";
        }

        return implode("\n", $rows);
    }
}
